### ISSUE TITLE
COGA Icons

### ISSUE THREAD

**Issue by lseeman** [w3c/i18n-activity#1007]
Hello I18n!

We are working on icons to replace icons in https://www.w3.org/TR/coga-usable/

The draft icons are at:
https://docs.google.com/document/d/1aRoYev1aAIHhIq37Itt96ueBwLh5zXMUeJBYxL0MCkQ/edit#

Can we ask you to take a look at the new drafts. Are there I18n issues?

We replaced using three fingers incase it has other meaning, but there may be issues we have missed.

Thanks so much 

lisa Seeman

**Comment by aphillips** [comment]
Adding to agenda of 2021-01-14 teleconference

@lseeman Do you have a date by which you need our feedback? Do you or someone else want to attend our discussion?

**Comment by r12a** [comment]
hello @lseeman. We use this repo for tracking issues only (although it could also be used for help with the review process and tools themselves).  So that it fits within our system i have moved your review request to https://github.com/w3c/i18n-request/issues/148.  (I have also added some text to the boilerplate for a new issue in this repo to explain that requests for review need to be raised there, and technical questions raised in a group's own repo with an i18n-tracker, to help people know what to do in future. Thanks for spotting a chink in our system ;-)

I will now close this issue in favour of the new issue i created.
