### ISSUE TITLE
ISO 4217 note commentary

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1045]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/payment-request/issues/949

**Comment by marcoscaceres** [comment]
CC @adrianhopebailie, who may have some suggestions on how we might reword the note.

**Comment by adrianhopebailie** [comment]
> Non-standard usage in particular seems like a Bad Idea.

@aphillips can you say why?

The goal here is to adhere to the format of ISO 4217 codes but not be restricted by the actual set of codes in the registry.

**Comment by r12a** [comment]
@marcoscaceres please don't hold technical discussions in these i18n-activity tracker issues (especially since they haven't even been reviewed by the i18n WG yet).  Discussions here should only be meta discussions about the status of the tracking.  One reason is that the payment-request WG cannot see discussions in these i18n-activity issues, another is that we have a process for managing review comments that these issues handle.  The technical discussion should take place in the issue we raise in the payment-request repo, if and when we raise one. Also, please don't ever close any issue in the i18n-activity tracker repo – that's only for the i18n WG to do after discussion. Thanks!

(You may see me making changes to the 13 issues you raised comments on or closed yesterday.)

**Comment by marcoscaceres** [comment]
No problem @r12a. Thanks for letting us know!

**Comment by aphillips** [comment]
Closed per discussion in telecon of 2021-09-09
