### ISSUE TITLE
Is input type=datetime implemented?

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#163]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/html/issues/462

**Comment by KatyMawhood** [comment]
I propose closing this issue because datetime (at-risk) feature has been removed from the [html5.1 branch in PR#530](https://github.com/w3c/html/pull/530).

**Comment by xfq** [comment]
It was removed in WHATWG HTML too: https://github.com/whatwg/html/issues/336

**Comment by KatyMawhood** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/05/02-i18n-minutes.html).

- Close #163
<details><summary><i class="differentiate">View the transcript</i></summary>
&lt;Katy> <a href="https://github.com/w3c/i18n-activity/issues/163">https://github.com/w3c/i18n-activity/issues/163</a><br/>
<b>addison:</b> lgtm<br/>
close<br/>
</details>
