### ISSUE TITLE
`validFrom` and `validUntil` fields need better specification of `dateTime`

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1729]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/vc-data-model/issues/1193

**Comment by msporny** [comment]
> A challenge of this data type is that it allows values both with (2023-06-15T00:00:00Z or 2023-06-15T00:00:00-08:00) and without (2023-06-15T00:00:00) time zone offsets. Since validFrom and validTo need to be interpreted as timestamp values, the spec should probably require that values without zone offsets be treated as being in the UTC time zone.

Yes, that's correct and why we're trying to change to XMLSCHEMA11-2 `dateTimeStamp`, which requires the usage of a timezone offset. We've already seen some examples in the wild that didn't include a timezone offset and thus were being interpreted as local timezone (instead of Zulu timezone). While we have no reports of this blowing up on people in the field, it's only a matter of time until it does, so we're requiring a timezone to be included in all `dateTimeStamp` values (which every date time field uses at present). This is what this PR is attempting to do: https://github.com/w3c/vc-data-model/pull/1183

All this to say that your feedback is valid and we're already trying to address the issue. Thank you for your feedback on PR https://github.com/w3c/vc-data-model/pull/1183 ... we're trying to incorporate your feedback into the PR now.

**Comment by aphillips** [comment]
Addressed
