### ISSUE TITLE
Specify byte or character value of `u`

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#1805]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/vc-di-bbs/issues/113

**Comment by himorin** [comment]
That header is coming from [VC Data Integrity](https://www.w3.org/TR/vc-data-integrity/#multibase-0), and I suppose this spec is better to write something like `Ensure the proofValue string is a multibase-base64url-no-pad-encoded value`, rather than just force to check `string starts with u`... (starting with `u` does not ensure the value is correctly encoded one or not.)

**Comment by aphillips** [comment]
Done. Fixed.
