### ISSUE TITLE
UTF-16 code points for addressable characters

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#216]
§ https://github.com/w3c/svgwg/issues/259

**Comment by klensin** [comment]
Whatever it is supposed to mean -- and I think someone is trying to get an approximation to a character count, the units should be Unicode code points or, if something insists, UTF-32 code units.  I'm not quite sure what a UTF-16 code unit is but strongly suspect it invites getting tied up with surrogate pairs in a way that would not be very helpful.  Of course, it the text is really looking for a count of what we used to call "orint positions", the above won't do it.

**Comment by aphillips** [comment]
@klensin I don't necessarily agree. The counting in SVG2 is supposed to be tied to DOM String, which is encoded in UTF-16 and uses UTF-16 code units for counting. The problem that @r12a is highlighting is that SVG introduced (a long time ago, in a specification far, far away---aka SVG1) different terminology instead of using code unit as the term. The term "addressable character" appears to mean "(index of a) UTF-16 code unit".  I agree that the current wording is excessively opaque. By not using standard Unicode terminology directly and by introducing confusing concepts such as "character addressing", the specification is much harder to understand (and that Unicode newbies will miss the implications entirely). But I also note that this terminology ship has sailed :-(. 

I think that what the text above is trying to say is:

> The address of a given Unicode character (codepoint) is measured in UTF-16 code units, prior to applying any text-transform conversions, as described for the methods in the SVGTextContentElement interface; as a result, a single Unicode character may be represented by multiple UTF-16 code units.

**Comment by klensin** [comment]
@Addison: Ok.  If that is what the text is trying to say, let's at least made it clear which, as it now stands, it isn't... and, IMO, that same text is likely to become less clear to readers over time.

The latter is a large part of what I'm concerned about, and it may be a fundamental philosophical problem.  I believe that the number of people who will be using the Internet and designing and implementing systems a decade hence, and especially the number who don't think of things primarily in terms of English written in Latin Script, will be vastly larger than than number today.  I want to see documents written now that speak to them, and are clear to them, at that time.  I think (or at least hope) that means terminology based on Unicode code points and that, if some encoding on the wire other than UTF-32 is appropriate, it is UTF-8.    If we have a legacy issue, or even a ship that has vanished over the horizon, I think we should be saying that explicitly and then either explaining things in modern/ contemporary/ future-looking terminology or or explaining things in the legacy language and then explicitly translating into modern terminology.    If we cannot do that, it is hard to imagine how we can make things better over time... and I just don't want to believe that we are stuck with the mistakes of the past forever, not because they are so trivial as to not worth the trouble to fix (which, pragmatically, I think we a good excuse) but because we are so far stuck in the ancient tar pits that improvements are impossible.

**Comment by r12a** [comment]
SVG WG closed the issue in favour of https://github.com/w3c/svgwg/issues/537, but it looks like they plan to move away from counting by utf-16 code units.  

I think we should keep this tracker item open until the dust settles, so we remember to check this point.

**Comment by aphillips** [comment]
This issue was subsumed by #606
