### ISSUE TITLE
 [encoding] Webkit support for GB18030

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#238]
https://bugs.webkit.org/show_bug.cgi?id=159891

**Comment by KatyMawhood** [comment]
Discussion continues on WhatWG, [gb18030 encoding/decoding support](https://github.com/whatwg/encoding/issues/57), with a ref to [web-platform-tests/wpt#3195](https://github.com/web-platform-tests/wpt/pull/3195) in Oct 2018.

@r12a, could you investigate/shall the i18n WG discuss?

**Comment by dragonthoughts** [comment]
The problem here seems to be that browser engines are inconsistent in their handling of the encoding processes. Since these tests seem to work on some engines where the Normalization is skipped, I feel that the tests should be validated, but that issues should be raised with the browser vendors, if they fail.

If the results of the same action on different browsers are not the same, this leads to compatiblity problems at the ECMA Script level.

**Comment by KatyMawhood** [comment]
@xfq, we were hoping that you could homogenise the tests for this issue in both cases. Would you be happy to do this?

**Comment by r12a** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/03/21-i18n-minutes.html#item08).

- `RESOLVED: ] make dormant`
<details><summary><i class="differentiate">View the transcript</i></summary>
&lt;Katy> <a href="https://github.com/w3c/i18n-activity/issues/238">https://github.com/w3c/i18n-activity/issues/238</a><br/>
<b>richard:</b> this is for encoding<br/>
... safari was doing some weird stuff<br/>
... main issue is that safari is out<br/>
... some aspects of tests are not correct<br/>
... meantime tests taken over by whatwg<br/>
... tests are complex<br/>
... haven't reviewed<br/>
... if xfq were here and were interested into looking into it that would be nice<br/>
... need a new tag for 'dormant'?<br/>
<b>[RESOLVED:</b>] make dormant<br/>
</details>
