### ISSUE TITLE
Remote Playback API > 2016-12-31

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#274]
https://w3c.github.io/remote-playback/

Requested: 2106-11-09

**Comment by anssiko** [comment]
When should we expect this i18n review to be completed?

We're preparing a CR publication of the Remote Playback API and this review is one of the remaining tasks blocking the publications. Thanks!

**Comment by aphillips** [comment]
@anssiko According to our records, we completed a review and forwarded all issues to you (there was only one: https://github.com/w3c/remote-playback/issues/70). Assuming that issue is addressed, you should be ready to proceed. Good luck with your progress to CR!

**Comment by anssiko** [comment]
Thanks for the review. The Second Screen WG will attempt to address the issue raised before advancing to CR.

**Comment by anssiko** [comment]
The WG fixed https://github.com/w3c/remote-playback/issues/70 with https://github.com/w3c/remote-playback/pull/99

You may close this issue to confirm your i18n feedback has been addressed.

**Comment by aphillips** [comment]
Consider for closure in telecon of 31 August

**Comment by anssiko** [comment]
It seems this issue was not discussed in telecon of 31 Aug per [minutes published]. 

We'd like to advance Remote Playback API to CR soon ([tracker]), and would prefer to get explicit closure from i18n to this issue prior.

[minutes published]: https://lists.w3.org/Archives/Public/www-international/2017JulSep/0086.html
[tracker]: https://github.com/w3c/remote-playback/issues/73

**Comment by steveatkin** [comment]
I am satisfied with the resolution of the issues. I think we can move forward.
