### ISSUE TITLE
tts:displayAlign should mention right-to-left effects

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#330]
https://w3c.github.io/ttml2/spec/ttml2.html#style-attribute-displayAlign

The style `tts:displayAlign` is written in such a way as to make `tts:direction=rtl` change what the keywords `before` and `after` mean. It says (in part):

> The tts:displayAlign attribute is used to specify a style property that defines the alignment of block areas in the block progression direction.

However, none of the examples include setting `tts:direction` or mention the effect of RTL presentation. Suggest that there be text that mentions this behavior.

**Comment by r12a** [comment]
I think it's actually ok, since it's talking about the _block progression direction_, which is perpendicular to the rtl/ltr alignment (i think that's called the _line progression direction_).

What's _not_ mentioned, however, is that this has a similar but rotated effect if the writing mode is set to a vertical value.

**Comment by aphillips** [comment]
closed as rejected
