### ISSUE TITLE
 Add navigator.locales to expose additional locale details

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#505]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/whatwg/html/pull/3046

**Comment by KatyMawhood** [comment]
I propose closing this issue because (a) the whatwg issue is now closed based on an i18n WG discussion, (b) it feels like a duplicate (or near duplicate) of our discussion in issue [#156 Should navigator.language and and/or HTTP Accept-Language include locale?](https://github.com/w3c/i18n-activity/issues/156)(now closed).
