### ISSUE TITLE
Tracking exception 'name' and 'explantation' fields not localized.

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#509]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/dnt/issues/63

Due to a process slip, the following comment should be viewed as part of the DNT response.

**Comment by dwsinger** [comment]
Since this is not widely deployed, I think we should do two things. Here's a strawman: (a) say that these fields are formed as HTML snippets (allowing plain text), allowing markup (which solves a host of problems, including this one and ruby) and (b) allow multiple instance of the fields, varying by language, which must be identified with a "lang" attribute on the top-level HTML construct (probably a "div"?) in the snippet.

**Comment by himorin** [comment]
change made https://github.com/w3c/dnt/commit/c885168130fdaf4fad5736711a7279836cd7f6d3, but not fully taken raised comments/suggestions from i18n WG

**Comment by r12a** [comment]
The latest published version of this spec is a [WG Note](https://www.w3.org/TR/2019/NOTE-tracking-dnt-20190117/).

**Comment by aphillips** [comment]
Closed unsatisfied in 2021-08-05
