### ISSUE TITLE
What should autocapitalize default be

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#519]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/html/issues/1092

**Comment by r12a** [comment]
Need to check status in WhatWG spec.

**Comment by KatyMawhood** [comment]
The WhatWG spec [autocap-hint-default](https://html.spec.whatwg.org/#autocap-hint-default) indicates that the default is determined by the UA and input method. I'd suggest that we close this.

**Comment by KatyMawhood** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/05/16-i18n-minutes.html).

- Close #519
<details><summary><i class="differentiate">View the transcript</i></summary>
I18N Issue Resolution<br/>
&lt;Katy> <a href="https://github.com/w3c/i18n-activity/issues/519">https://github.com/w3c/i18n-activity/issues/519</a><br/>
<b>RESOLUTION:</b> close<br/>
</details>
