### ISSUE TITLE
URI developments

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#52]
Raised by:Addison Phillips
Opened on:2014-11-26

http://www.w3.org/TR/xslt-30/#uri-references

This section defines URI as:

> [Definition: Within this specification, the term URI Reference, unless otherwise stated, refers to a string in the lexical space of the xs:anyURI datatype as defined in [XML Schema Part 2].] Note that this is a wider definition than that in [RFC3986]: in particular, it is designed to accommodate Internationalized Resource Identifiers (IRIs) as described in [RFC3987], and thus allows the use of non-ASCII characters without escaping.

This is a Good Thing, but continuing developments in the URI/IRI/URL space need to be tracked. I don't see any specific changes needed now: I'm creating this as a tracking issue.

**Comment by KatyMawhood** [comment]
This spec is now a Rec, therefore I propose to close this issue.

**Comment by KatyMawhood** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/03/28-i18n-minutes.html).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
&lt;Katy> <a href="https://github.com/w3c/i18n-activity/issues/52">https://github.com/w3c/i18n-activity/issues/52</a><br/>
<b>katy:</b> 3 looking to close. that's the first one<br/>
... that's now part of a rec<br/>
close<br/>
<b>RESOLUTION:</b> close issue 52<br/>
</details>

**Comment by r12a** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/03/28-i18n-minutes.html).

- `RESOLVED:  close issue 52`
<details><summary><i class="differentiate">View the transcript</i></summary>
&lt;Katy> <a href="https://github.com/w3c/i18n-activity/issues/52">https://github.com/w3c/i18n-activity/issues/52</a><br/>
<b>katy:</b> 3 looking to close. that's the first one<br/>
... that's now part of a rec<br/>
close<br/>
<b>RESOLVED:</b> close issue 52<br/>
</details>
