### ISSUE TITLE
Clarify precedence of font-presentation versus lang/xml:lang

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#525]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/2138

**Comment by KatyMawhood** [comment]
I propose closing this issue because this is now clarified in [css-fonts-4](https://drafts.csswg.org/css-fonts-4/); [issue #2138](https://github.com/w3c/csswg-drafts/issues/2138) is closed. 

> BCP47’s -u- extension to the language tag accepted by lang or xml:lang should not be considered when the user-agent decides whether to use emoji presentation or text presentation for a particular character.

**Comment by KatyMawhood** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/05/02-i18n-minutes.html).

- Close #525
<details><summary><i class="differentiate">View the transcript</i></summary>
<a href="https://github.com/w3c/i18n-activity/issues/525">https://github.com/w3c/i18n-activity/issues/525</a><br/>
lgtm<br/>
close 525<br/>
</details>
