### ISSUE TITLE
autocapitalize description

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-activity#573]
4.10.5.3.11. The autocapitalize attribute
https://www.w3.org/TR/html53/sec-forms.html#element-attrdef-input-autocapitalize

> Any alphabetical character preceeded by a non-alphabetical character

> Normal prose capitalization rules: typically the first letter in a string, the first letter after a period ('.'), colon (':'), question mark ('?'), or exclamation point ('!'). Other words may begin with an upper-case letter, although this varies by language. 

The descriptions of the autocapitalize states (`words`, `sentences`, `characters`) don't seem quite right. The term "any alphabetical character" is meant to convey that it doesn't apply to e.g. punctuation. But it really means any cased character in a bicameral script. 

The description of `words` (the first quote above) suggests that `123Abc` would be correct, since `3` isn't an alphabetical character.

The "normal prose capitalization" also strikes me as slightly problematic. 

On a higher level, I'd prefer to see that the wording be more suggestive of what this actually is: a hint to modal keyboards/IMEs, such as mobile ones.

**Comment by KatyMawhood** [comment]
I propose that we raise an issue to [w3c/html](https://github.com/w3c/html/issues/new).

**Comment by r12a** [comment]
The issue needs to go to the whatwg nowadays.

**Comment by aphillips** [comment]
Based on my action item, I reviewed the [current text](https://html.spec.whatwg.org/multipage/interaction.html#autocapitalization) of the whatwg spec. The problem text originally cited is no longer present. I probably have some nit comments about the text that is there now, but the over-specificity has been resolved. Suggest we close.

**Comment by KatyMawhood** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/04/11-i18n-minutes.html).

- Closed #573
<details><summary><i class="differentiate">View the transcript</i></summary>
&lt;Katy> <a href="https://github.com/w3c/i18n-activity/issues/573">https://github.com/w3c/i18n-activity/issues/573</a><br/>
<a href="https://html.spec.whatwg.org/multipage/interaction.html#autocapitalization">https://html.spec.whatwg.org/multipage/interaction.html#autocapitalization</a><br/>
"different language keyboards should provide language specific behavior for each of these keywords"<br/>
close this, make new issue<br/>
</details>
