### ISSUE TITLE
Proposal for handling localizable texts (writeup of the F2F discussions)

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#666]
An attempt for a write-up for the result of the discussion on language and direction of the F2F in Lyon on how to handle localizable texts in the Web Publication Manifest.

**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wpub/issues/354

**Comment by r12a** [comment]
We're somehow late in adding this to our tracker db. I added it as a comment (rather than tracking) because Addison was actioned by the i18n WG to intervene on the thread.

**Comment by himorin** [comment]
New issue https://github.com/w3c/wpub/issues/440 has filed to discuss on the editorial aspect of the document.

**Comment by KatyMawhood** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/05/16-i18n-minutes.html).

- Close #666
<details><summary><i class="differentiate">View the transcript</i></summary>
<a href="https://lists.w3.org/Archives/Member/member-i18n-core/2019May/0024.html">https://lists.w3.org/Archives/Member/member-i18n-core/2019May/0024.html</a><br/>
close 666?<br/>
<b>RESOLUTION:</b> close 666<br/>
</details>
