### ISSUE TITLE
[css-text] U+205F Medium Mathematical Space (MMSP) not mentioned

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#689]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/csswg-drafts/issues/3878
U+205F Medium Mathematical Space is not mentioned in list of samples for 'General punctuation and fixed-width spaces'

**Comment by himorin** [comment]
CSS WG added an editorial clarification to mention samples
  https://github.com/w3c/csswg-drafts/commit/6030c88e7688e7e34998a4aba7a9c083e8fdbb0f

**Comment by KatyMawhood** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/05/16-i18n-minutes.html).

- Close #689
<details><summary><i class="differentiate">View the transcript</i></summary>
&lt;Katy>  <a href="https://github.com/w3c/i18n-activity/issues/689">https://github.com/w3c/i18n-activity/issues/689</a><br/>
LGTM<br/>
<b>RESOLUTION:</b> close<br/>
</details>
