### ISSUE TITLE
 i18n checklist for Working with numbers

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#692]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wot-thing-description/issues/579

**Comment by himorin** [comment]
Check completed. Numeric values to be exchanged are on JSON or XML Schemas, display are free to apply shaping by user's preferences.

**Comment by KatyMawhood** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/05/16-i18n-minutes.html).

- Close WoT issues listed in weekly mail
<details><summary><i class="differentiate">View the transcript</i></summary>
https://lists.w3.org/Archives/Member/member-i18n-core/2019May/0024.html<br/>
close all wot issues in atsushi's email?<br/>
<b>RESOLUTION:</b> close WoT issues listed in weekly mail<br/>
</details>
