### ISSUE TITLE
i18n checklist for declaring language at the resource level

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-activity#694]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wot-thing-description/issues/584

**Comment by himorin** [comment]
For fields "support", "description", "title" and "name" in TD spec, "name" was removed, "support" changed to type anyURI, and "description" and "title" have corresponding multi-language fields (ending with plural s) for I18N with metadata @language.

**Comment by KatyMawhood** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/05/16-i18n-minutes.html).

- Close WoT issues listed in weekly mail
<details><summary><i class="differentiate">View the transcript</i></summary>
https://lists.w3.org/Archives/Member/member-i18n-core/2019May/0024.html<br/>
close all wot issues in atsushi's email?<br/>
<b>RESOLUTION:</b> close WoT issues listed in weekly mail<br/>
</details>
