### ISSUE TITLE
Wording for application of base direction

### ISSUE THREAD

**Issue by himorin** [w3c/i18n-activity#699]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/wpub/issues/440

Issue to discuss on wording for application of base direction in section 2.6.3.4.2 Item-specific Language.

**Comment by r12a** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2019/05/16-i18n-minutes.html#item06).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
wording for wpub<br/>
&lt;r12a> <a href="https://github.com/w3c/wpub/issues/440#issuecomment-493040722">https://github.com/w3c/wpub/issues/440#issuecomment-493040722</a><br/>
<b>richard:</b> discussion between ivan and najib currently<br/>
<b>&lt;najib&gt;</b> Almost finished<br/>
<b>&lt;r12a&gt;</b> <a href="https://w3c.github.io/wpub/#app-bidi-examples">https://w3c.github.io/wpub/#app-bidi-examples</a><br/>
<b>addison:</b> LGTM<br/>
</details>

**Comment by r12a** [comment]
WPub issue is closed.
