### ISSUE TITLE
Attribute with natural language but no language

### ISSUE THREAD

**Issue by bert-github** [w3c/i18n-activity#996]
**This is a tracker issue.** Only discuss things here if they are i18n WG internal meta-discussions about the issue. **Contribute to the actual discussion at the following link:**

§ https://github.com/w3c/aria/issues/1365

**Comment by xfq** [comment]
WG issue closed. They added some clarification to the translatable attributes section.

Current spec text: https://w3c.github.io/aria/#translatable-attributes

**Comment by r12a** [comment]
I can't see how their edits address the original question.  As i understand it, it's about labelling text for lang & direction, rather than translatability.

**Comment by aphillips** [comment]
I think that what they are trying to say is that the "translateable" `aria-*` attributes should match the language of the host element (because the `lang` attribute of the host element defines the language). The section they modified ([Translateable Attributes](https://w3c.github.io/aria/#translatable-attributes)) primarily talks about the need to match the natural language ARIA attributes to the language of the host element. 

I tend to agree with you that they should be more direct in stating that these attributes get their natural language metadata from the host element. I observe that the specification of the attributes in question (cf. [`aria-value`](https://w3c.github.io/aria/#aria-valuetext)) do not talk about language metadata. I would prefer if each element were explicit about it.

**Comment by xfq** [comment]
I propose that we close this tracker issue per https://github.com/w3c/aria/issues/1761#issuecomment-1184543932
